name: magicml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - boto3
  - aws-xray-sdk
  - pandas
  - numpy
  - pyarrow
  - python-dotenv
  - ipywidgets
  - matplotlib
  - requests
  - pytest
  - coverage
  - pip
  - pip:
    - sagemaker
    - docker-compose