service: magicml-ecr-offline

custom: ${file(../serverless.common.yml):custom}

package:
  individually: true
  exclude:
    - package-lock.json
    - package.json
  include:
    - ../libs/**

provider:
  name: aws
  stage: dev
  region: us-east-1
  useDotenv: true
  profile: lw2134
  lambdaHashingVersion: 20201221
  ecr:
    images:
      ST_image:
        path: ../
        file: st.Dockerfile
      processing_image:
        path: ../
        file: processing.Dockerfile

functions:
  dummy_ST:
    image:
      name: ST_image
      command:
        - api.dummy
      entryPoint:
        - '/lambda-entrypoint.sh'
    memorySize: 128
    timeout: 60
    maximumRetryAttempts: 0
    events:
      - http:
          path: dummy_ST
          method: get
          cors: true

  dummy_processing:
    image:
      name: processing_image
      command:
        - api.dummy
      entryPoint:
        - '/lambda-entrypoint.sh'
    memorySize: 128
    timeout: 60
    maximumRetryAttempts: 0
    events:
      - http:
          path: dummy_processing
          method: get
          cors: true