AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SimilarityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.similarity_table}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

Outputs:
  SimilarityTableArn:
    Value:
       Fn::GetAtt:
        - SimilarityTable
        - Arn
    Export:
      Name: ${self:custom.stage}-SimilarityTableArn