AWSTemplateFormatVersion: '2010-09-09'
Resources:
  USEModel:
    Type: 'AWS::SageMaker::Model'
    Properties:
      ModelName: 'use-large'
      Containers:
        - Image: '763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:2.3-cpu'
          ModelDataUrl: 's3://magicml-models.dev/use-large/model.tar.gz'
      ExecutionRoleArn: 'arn:aws:iam::553371509391:role/magicml-sagemaker'

Outputs:
  USEModelArn:
    Value:
       Fn::GetAtt:
        - USEModel
        - Arn
    Export:
      Name: ${self:custom.stage}-USEModelArn

  USEModelName:
    Value:
      Ref: USEModel
    Export:
      Name: ${self:custom.stage}-USEModel