AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SimilarityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.similarity_table}
      AttributeDefinitions:
        - AttributeName: scryfallId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: scryfallId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: name-index
          KeySchema:
          - AttributeName: name
            KeyType: HASH
          Projection:
            ProjectionType: ALL
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

Outputs:
  SimilarityTableArn:
    Value:
       Fn::GetAtt:
        - SimilarityTable
        - Arn
    Export:
      Name: ${self:custom.stage}-SimilarityTableArn