AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SagemakerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: '*'
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'

Outputs:
  SagemakerRoleARN:
    Description: Sagemaker Role ARN
    Value: !GetAtt SagemakerRole.Arn
    Export:
      Name: SagemakerRoleARN-${self:custom.stage}