AWSTemplateFormatVersion: '2010-09-09'
Resources:
# EFS Resources
  # EFSA
  fileSystemA:
    Type: AWS::EFS::FileSystem
  
  mountTargetA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref fileSystemA
      SubnetId: !Ref privateSubnetA
      SecurityGroups:
        - !GetAtt privateVPC.DefaultSecurityGroup
  
  accessPointA: # data_prep Service Access Point
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref fileSystemA
      PosixUser:
        Uid: "1001"
        Gid: "1001"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1001"
          OwnerUid: "1001"
          Permissions: "755"
        Path: ${self:custom.data_prep_mnt_path}
  
  # Private VPC
  privateVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
  
  privateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref privateVPC
      AvailabilityZone:
        Fn::Select:
         - 0
         - Fn::GetAZs: ""
      CidrBlock: 172.16.0.0/20
  
  privateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref privateVPC
  
  privateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref privateSubnetA
      RouteTableId: !Ref privateRouteTable

  vpcEndpointLambdaSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        VpcId: !Ref privateVPC

  vpcEndpointSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        VpcId: !Ref privateVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 443
            ToPort: 443
            SourceSecurityGroupId: !GetAtt vpcEndpointLambdaSecurityGroup.GroupId
  
  s3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - !Ref privateRouteTable
      ServiceName: 'com.amazonaws.${self:provider.region}.s3'
      VpcId: !Ref privateVPC

  dynamoEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - !Ref privateRouteTable
      ServiceName: 'com.amazonaws.${self:provider.region}.dynamodb'
      VpcId: !Ref privateVPC

  lambdaEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: True
      SecurityGroupIds: 
        - !GetAtt vpcEndpointSecurityGroup.GroupId
      SubnetIds:
        - !Ref privateSubnetA
      ServiceName: 'com.amazonaws.${self:provider.region}.lambda'
      VpcId: !Ref privateVPC

  sagemakerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: True
      SecurityGroupIds: 
        - !GetAtt vpcEndpointSecurityGroup.GroupId
      SubnetIds:
        - !Ref privateSubnetA
      ServiceName: 'com.amazonaws.${self:provider.region}.sagemaker.api'
      VpcId: !Ref privateVPC


Outputs:
  privateVPCSecurityGroup:
    Description: Default security for Lambda VPC
    Value: !GetAtt privateVPC.DefaultSecurityGroup
    Export:
      Name: VPCSecGroupID-${self:custom.stage}
  privateVPCID:
    Description: VPC ID
    Value: !Ref privateVPC
    Export:
      Name: VPCID-${self:custom.stage}
  privateSubnetAID:
    Description: Private Subnet A ID
    Value: !Ref privateSubnetA
    Export:
      Name: VPCSubnetAID-${self:custom.stage}
  fileSystemAId:
    Description: File system ID
    Value: !Ref fileSystemA
    Export:
      Name: EFSAID-${self:custom.stage}
  mountTargetA:
    Description: Mount point A ID
    Value: !Ref mountTargetA
    Export:
      Name: MountTargetAID-${self:custom.stage}
  accessPointAArn:
    Description: Access point ARN
    Value: !GetAtt accessPointA.Arn
    Export:
      Name: EFSAccessPointAARN-${self:custom.stage}